Silence errtrace When Queue Empty
"ls -A" prints a backtrace when the queue directory is empty due to
the errtrace shell option. This commit replaces the call to "ls -A"
with a pure bash function which checks the queue directory for any
message files, and will not trigger a backtrace even when the errtrace
option is set.

(cherry picked from commit 069369a261083254dc828cfab597407d80315706)

diff --git a/scripts/msmtpq/msmtpq b/scripts/msmtpq/msmtpq
--- a/scripts/msmtpq/msmtpq
+++ b/scripts/msmtpq/msmtpq
@@ -375,10 +375,22 @@ send_queued_mail() {   # <-- mail id
   fi                                                           # (but allow continuation)
 }
 
+is_queue_dir_empty() {
+    # - "shopt -p" is available as of bash 2.01.1
+    # - "trap ... RETURN" is available as of bash 2.05b
+    # - the return value of shopt must be ignored (the manual says:
+    #   "The return status when listing options is zero if all
+    #   optnames are enabled, non-zero otherwise.")
+    trap "$(shopt -p nullglob || true)" RETURN
+    shopt -s nullglob
+    files=( "$MSMTPQ_Q"/*.mail )
+    (( ${#files[@]} == 0 ))
+}
+
 ## run (flush) queue
 ##
 run_queue() {    # <- 'sm' mode      # run queue
-  if [ -z "$(ls -A "$MSMTPQ_Q"/*.mail 2>/dev/null)" ]; then
+  if is_queue_dir_empty ; then
     [ -n "$1" ] || dsp '' 'mail queue is empty (nothing to send)' ''
     return
   fi
@@ -398,7 +410,7 @@ run_queue() {    # <- 'sm' mode      # run queue
 ## display queue contents
 ##
 display_queue() {      # <-- { 'purge' | 'send' } (op label) ; { 'rec' } (record array of mail ids)
-  if [ -z "$(ls -A "$MSMTPQ_Q"/*.mail 2>/dev/null)" ]; then
+  if is_queue_dir_empty ; then
     if [ -z "$1" ]; then
       dsp '' 'no mail in queue' ''
     else
